default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: tweet_exam_development
test:
  <<: *default
  database: tweet_exam_test
production:
  <<: *default
  database: tweet_exam_production
  username: tweet_exam
  password: <%= ENV['TWEET_EXAM_DATABASE_PASSWORD'] %>
